import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitbod App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="fitbod-header">
          <Link href="/">
            <Image
              src="/fitbodLogo.svg"
              alt="Fitbod Logo"
              className="fitbod-logo"
              width={160}
              height={24}
              priority
            />
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
